FROM quay.io/keycloak/keycloak:24.0.1

USER root

# Copy theme
COPY keycloak-theme /opt/keycloak/themes/timey
RUN chown -R keycloak:keycloak /opt/keycloak/themes/timey

# Copy realm export file
COPY keycloak-theme/realm-export.json /opt/keycloak/data/import/realm-export.json
RUN chown keycloak:keycloak /opt/keycloak/data/import/realm-export.json

USER keycloak

