/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RedirectImport } from './routes/redirect'
import { Route as MethodsImport } from './routes/methods'
import { Route as UsersRouteImport } from './routes/users.route'
import { Route as IndexImport } from './routes/index'
import { Route as UsersIndexImport } from './routes/users.index'
import { Route as SequenceIndexImport } from './routes/sequence.index'
import { Route as UsersUserIdImport } from './routes/users.$userId'
import { Route as ModuleIdImport } from './routes/module.$id'
import { Route as MethodIdImport } from './routes/method.$id'

// Create/Update Routes

const RedirectRoute = RedirectImport.update({
  id: '/redirect',
  path: '/redirect',
  getParentRoute: () => rootRoute,
} as any)

const MethodsRoute = MethodsImport.update({
  id: '/methods',
  path: '/methods',
  getParentRoute: () => rootRoute,
} as any)

const UsersRouteRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UsersIndexRoute = UsersIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsersRouteRoute,
} as any)

const SequenceIndexRoute = SequenceIndexImport.update({
  id: '/sequence/',
  path: '/sequence/',
  getParentRoute: () => rootRoute,
} as any)

const UsersUserIdRoute = UsersUserIdImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => UsersRouteRoute,
} as any)

const ModuleIdRoute = ModuleIdImport.update({
  id: '/module/$id',
  path: '/module/$id',
  getParentRoute: () => rootRoute,
} as any)

const MethodIdRoute = MethodIdImport.update({
  id: '/method/$id',
  path: '/method/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRoute
    }
    '/methods': {
      id: '/methods'
      path: '/methods'
      fullPath: '/methods'
      preLoaderRoute: typeof MethodsImport
      parentRoute: typeof rootRoute
    }
    '/redirect': {
      id: '/redirect'
      path: '/redirect'
      fullPath: '/redirect'
      preLoaderRoute: typeof RedirectImport
      parentRoute: typeof rootRoute
    }
    '/method/$id': {
      id: '/method/$id'
      path: '/method/$id'
      fullPath: '/method/$id'
      preLoaderRoute: typeof MethodIdImport
      parentRoute: typeof rootRoute
    }
    '/module/$id': {
      id: '/module/$id'
      path: '/module/$id'
      fullPath: '/module/$id'
      preLoaderRoute: typeof ModuleIdImport
      parentRoute: typeof rootRoute
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdImport
      parentRoute: typeof UsersRouteImport
    }
    '/sequence/': {
      id: '/sequence/'
      path: '/sequence'
      fullPath: '/sequence'
      preLoaderRoute: typeof SequenceIndexImport
      parentRoute: typeof rootRoute
    }
    '/users/': {
      id: '/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexImport
      parentRoute: typeof UsersRouteImport
    }
  }
}

// Create and export the route tree

interface UsersRouteRouteChildren {
  UsersUserIdRoute: typeof UsersUserIdRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

const UsersRouteRouteChildren: UsersRouteRouteChildren = {
  UsersUserIdRoute: UsersUserIdRoute,
  UsersIndexRoute: UsersIndexRoute,
}

const UsersRouteRouteWithChildren = UsersRouteRoute._addFileChildren(
  UsersRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/users': typeof UsersRouteRouteWithChildren
  '/methods': typeof MethodsRoute
  '/redirect': typeof RedirectRoute
  '/method/$id': typeof MethodIdRoute
  '/module/$id': typeof ModuleIdRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/sequence': typeof SequenceIndexRoute
  '/users/': typeof UsersIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/methods': typeof MethodsRoute
  '/redirect': typeof RedirectRoute
  '/method/$id': typeof MethodIdRoute
  '/module/$id': typeof ModuleIdRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/sequence': typeof SequenceIndexRoute
  '/users': typeof UsersIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/users': typeof UsersRouteRouteWithChildren
  '/methods': typeof MethodsRoute
  '/redirect': typeof RedirectRoute
  '/method/$id': typeof MethodIdRoute
  '/module/$id': typeof ModuleIdRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/sequence/': typeof SequenceIndexRoute
  '/users/': typeof UsersIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/users'
    | '/methods'
    | '/redirect'
    | '/method/$id'
    | '/module/$id'
    | '/users/$userId'
    | '/sequence'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/methods'
    | '/redirect'
    | '/method/$id'
    | '/module/$id'
    | '/users/$userId'
    | '/sequence'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/users'
    | '/methods'
    | '/redirect'
    | '/method/$id'
    | '/module/$id'
    | '/users/$userId'
    | '/sequence/'
    | '/users/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UsersRouteRoute: typeof UsersRouteRouteWithChildren
  MethodsRoute: typeof MethodsRoute
  RedirectRoute: typeof RedirectRoute
  MethodIdRoute: typeof MethodIdRoute
  ModuleIdRoute: typeof ModuleIdRoute
  SequenceIndexRoute: typeof SequenceIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UsersRouteRoute: UsersRouteRouteWithChildren,
  MethodsRoute: MethodsRoute,
  RedirectRoute: RedirectRoute,
  MethodIdRoute: MethodIdRoute,
  ModuleIdRoute: ModuleIdRoute,
  SequenceIndexRoute: SequenceIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/users",
        "/methods",
        "/redirect",
        "/method/$id",
        "/module/$id",
        "/sequence/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/users": {
      "filePath": "users.route.tsx",
      "children": [
        "/users/$userId",
        "/users/"
      ]
    },
    "/methods": {
      "filePath": "methods.tsx"
    },
    "/redirect": {
      "filePath": "redirect.tsx"
    },
    "/method/$id": {
      "filePath": "method.$id.tsx"
    },
    "/module/$id": {
      "filePath": "module.$id.tsx"
    },
    "/users/$userId": {
      "filePath": "users.$userId.tsx",
      "parent": "/users"
    },
    "/sequence/": {
      "filePath": "sequence.index.tsx"
    },
    "/users/": {
      "filePath": "users.index.tsx",
      "parent": "/users"
    }
  }
}
ROUTE_MANIFEST_END */
